{% set name = "gofit" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gofit-{{ version }}.tar.gz
  sha256: ab5b578e641db5fe590627d0165abac67eaae9cc5a1451d3d6aceb3a2635e136

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - ninja
    - pip
    - pybind11
    - eigen
    - cmake
    - make
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pip
    - numpy
  imports:
    - gofit
  commands:
    - pip check
    - cd tests
    - python test_regularisation.py
    - python test_alternating.py
    - python test_multistart.py
    - python test_multistart_ls.py

about:
  home: https://github.com/ralna/gofit
  summary: 'GOFit: Global Optimization for Fitting problems'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jess-farmer
    - jfowkes
