{% set name = "gofit" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gofit-{{ version }}.tar.gz
  sha256: 518c2aa0a82bda3571acfd67fe91ccd4064b77076226ca30e1e4f97eedadad6e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - ninja
    - pip
    - setuptools
    - pybind11
    - eigen
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pip
    - numpy
  imports:
    - gofit
  commands:
    - pip check
    - cd tests
    - python test_regularisation.py
    - python test_alternating.py
    - python test_multistart.py
    - python test_multistart_ls.py

about:
  home: https://github.com/ralna/gofit
  summary: 'GOFit: Global Optimization for Fitting problems'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jess-farmer
    - jfowkes
